language:
  - cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - cmake
    - build-essential
    - libeigen3-dev

before_install:
  - sudo add-apt-repository ppa:timsc/opencv-3.3
  - sudo apt update
  - sudo apt install opencv

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && make test
