language:
  - cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - cmake
    - build-essential
    - libeigen3-dev

before_install:
  - sudo add-apt-repository -y ppa:ulikoehler/opencv3
  - sudo apt update
  - sudo apt install libopencv3

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && make test
