language:
  - cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - cmake
    - build-essential
    - libeigen3-dev
    - libvtk6-dev

before_install:
  - git clone https://github.com/opencv/opencv_contrib.git
  - cd opencv_contrib
  - git checkout 3.3.1
  - cd ..
  - git clone https://github.com/opencv/opencv.git
  - cd opencv
  - git checkout 3.3.1
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DWITH_VTK=ON ..
  - make -j2
  - sudo make install

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && make test
