language:
  - cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - cmake
    - build-essentials
    - eigen
    - opencv

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && make test
